updated condition

diff --git a/.github/workflows/create-mwodda-solution-config-dev.yaml b/.github/workflows/create-mwodda-solution-config-dev.yaml
--- a/.github/workflows/create-mwodda-solution-config-dev.yaml
+++ b/.github/workflows/create-mwodda-solution-config-dev.yaml
@@ -83,7 +83,11 @@ jobs:
           echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV
           git checkout -b $branch_name
 
-
+      - name: Check if logic_app is enabled without storage_account
+        if: ${{ inputs.enable_logic_app == 'true' && inputs.enable_storage_accounts == 'false' }}
+        run: |
+          echo "Error: logic_app requires storage_account to be enabled."
+          exit 1
       - name: Create config file
         run: |
           dest_config_dir_path="development/${{ env.SOLUTION_PREFIX }}-${{ env.solution_product_short_name }}-EUS2"
@@ -118,12 +122,7 @@ jobs:
           if ${{ inputs.enable_storage_accounts }}; then
             cat templates/mwodda-snacking-solution-config-template/development/tf_config/parts/storage_accounts.txt >> $config_file
           fi
-
-          # Check if logic_app is enabled without storage_account
-          if: ${{ inputs.enable_logic_app == 'true' && inputs.enable_storage_accounts == 'false' }}
-          run: |
-            echo "Error: logic_app requires storage_account to be enabled."
-            exit 1
+          
 
           # Conditionally include logic_app block
           if ${{ inputs.enable_logic_app == 'true' }} && ${{ inputs.enable_storage_accounts == 'true' }}; then
